name: Test Environment Variables

on:
  push:
    branches:
      - main
jobs:
  example:
    runs-on: ubuntu-latest
    env:
      BASE_URL: "https://example.com"
    steps:
      - name: Define FULL_URL
        env:
          FULL_URL: ${{ env.BASE_URL }}/path
        run: echo $FULL_URL


